version: "3.8"

services:
  input:
    image: "weather-input"
    build:
      context: ./service-a
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_URL=otel-collector:4317
      - ORCHESTRATOR_URL=http://orchestrator:8181
    depends_on:
      - otel-collector

  orchestrator:
    image: "weather-orchestrator"
    build:
      context: ./service-b
    ports:
      - "8181:8181"
    environment:
      - OTEL_EXPORTER_URL=otel-collector:4317
    env_file:
      - ./service-b/.env
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "4317:4317" # OTLP gRPC receiver

  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
